# Change these first
owner: ainanaailala # Your GitHub username
repo: upptime # Your Github repository name

sites:
- name: drpy-replit
- url: https://drpy.ainanaailala.repl.co/config/2

status-website:
repo: upptime # Your Github repository name
  logoUrl: https://drpy.ainanaailala.repl.co/config/2
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: ainanaailala
      href: https://drpy.ainanaailala.repl.co/config/2

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
